CREATE TABLE supplier1 (
SNO TEXT PRIMARY KEY,
SNAME TEXT,
STATUS INTEGER,
CITY TEXT);

INSERT INTO supplier1 (SNO,SNAME,STATUS,CITY) VALUES
("S1" , "RAIDAH", 17,"DHAKA"),
("S2" , "TUNA", 17,"DHAKA"),
("S3" , "TAIMA", 17,"DHAKA"),
("S4" , "RAFA", 17,"DHAKA");

SELECT * FROM supplier1;