CREATE TABLE IF NOT EXISTS PRODUCT (
ID TEXT PRIMARY KEY,
NAME TEXT NOT NULL,
PRICE REAL,
COM TEXT);

INSERT INTO  PRODUCT (ID, NAME, PRICE,COM) VALUES
('1','DVD',200,'12'),
('2','KEYBOARD',350,'14'),
('3','SPEAKER',3200,'15'),
('4','MONITOR',500,'13'),
('5','WIRE',600,'09'),
('6','MOUSE',500,'08'),
('7','DRIVE',1000,'21'),
('8','USD',900,'23');

SELECT NAME , PRICE FROM PRODUCT 
WHERE PRICE = (SELECT MIN(PRICE) FROM PRODUCT);

SELECT NAME , PRICE FROM PRODUCT 
WHERE PRICE = (SELECT MAX(PRICE) FROM PRODUCT);