CREATE TABLE IF NOT EXISTS STUDENTS0 (
ROLL_NO TEXT PRIMARY KEY,
NAME TEXT NOT NULL,
ADDRESS TEXT,
PHONE TEXT,
AGE INTEGER);

INSERT INTO STUDENTS0 (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('1', 'RAM', 'DEHLI','*****',18), 
('2', 'RAMESH', 'GURGAON','*****',20), 
('3', 'SUJIT', 'ROHTAK','*****',18), 
('4', 'RAMAN', 'DEHLI','*****',20), 
('5', 'HARSH', 'ROHTAK','*****',18);

SELECT * FROM STUDENTS0;

SELECT * FROM STUDENTS0 WHERE AGE = 18 AND ADDRESS = 'DEHLI';

SELECT * FROM STUDENTS0 WHERE NAME = 'RAM' OR NAME = 'HARSH';

SELECT * FROM STUDENTS0 WHERE NAME = 'RAM' OR AGE = 20;

SELECT * FROM STUDENTS0 WHERE AGE = 18 AND ( NAME = 'RAM' OR NAME = 'HARSH');